apiVersion: v1
kind: Service
metadata:
  labels:
    run: dotnet-app
  name: dotnet-app
  namespace: dotnetapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    run: dotnet-app
  type: LoadBalancer
