apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  namespace: dotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - image: dotnetapp:v1
        imagePullPolicy: IfNotPresent
        name: dotnetapp
        ports:
        - containerPort: 8000
          protocol: TCP
