apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jenkins.labels }}-pvc
  namespace: {{ .Values.jenkins.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
  volumeMode: Filesystem
