apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.jenkins.labels }}-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.jenkins.labels }}-pvc
    namespace: {{ .Values.jenkins.namespace }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
